x-common-variables: &common-variables
  PLANTUML_JAR: /opt/plantuml.jar

services:
  python:
    image: python
    environment: *common-variables
  java:
    image: plantuml/plantuml
    environment: *common-variables