name: CI

on:
    workflow_dispatch:
    push:
        branches: [ main ]
    pull_request:
        branches: [ '*' ]

jobs:
    github-setup-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This job was automatically triggered by a ${{ github.event_name }} event"
            - run: echo "This job is now running on a ${{ runner.os }}" server hosted by GitHub
            - run: echo "The name of your branch is ${{ github.ref }}" and your repository is ${{ github.repository}}
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "The ${{ github.repository }} has been cloned to the runner."
            - run: echo "The workflow is now ready to test your code on the runner"
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: echo "This job status is ${{ job.status }}"
    tests:
        runs-on:
            ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                
            - name: Install package and dependencies for testing
              run: pip install .
            
            - name: Run tests
              shell: bash
              run: pytest --cov --cov-report=term-missing --color=yes
