name: Container

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  build:
    runs-on:
      ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Start container
      shell: bash
      run: |
        docker build -t volleyballplayer/design-patterns:1.0 . --progress=plain --no-cache
        docker run -it --name design-patterns volleyballplayer/design-patterns:1.0
        source /design-patterns/.venv/bin/activate

    - name: Run patterns
      shell: bash
      run: |
        run-creational-pattern factory-method
        run-creational-pattern builder
        run-creational-pattern abstract-factory
        run-creational-pattern singleton
        run-creational-pattern prototype

        run-structural-pattern adapter

    - name: Stop container
      if: always()
      run: docker container rm $(docker container ls -aq)
