name: Documentation

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: 
      ubuntu-latest
    permissions:
      contents: write

    steps:      
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Start container
      shell: bash
      run: |
        docker --version
        docker-compose -f design-patterns-docker-compose.yaml up -d
      
    - name: Install package and dependencies for building the documentation
      shell: bash
      run: pip install -e .[docs]

    - name: Call sphinx-apidoc for automatic API documentation
      shell: bash
      run: source docs/source/call_sphinx_apidoc.sh

    - name: Build documentation
      shell: bash
      working-directory: ./docs
      run: |
        sphinx-build -b html -E source html

    - name: Documentation coverage
      shell: bash
      run: |
        sphinx-build -M coverage ./docs/source ./docs/coverage

    - name: Deploy
      if: (github.event_name == 'release' && github.event.release.target_commitish == 'main') || (github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'push'))
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html

    - name: Stop container
      if: always()
      run: docker-compose -f design-patterns-docker-compose.yaml down

    
